/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type AlbumAddMedia,
  AlbumAddMediaFromJSON,
  AlbumAddMediaToJSON,
} from "../models/AlbumAddMedia";
import {
  type AlbumInsertData,
  AlbumInsertDataFromJSON,
  AlbumInsertDataToJSON,
} from "../models/AlbumInsertData";
import {
  type AlbumResponse,
  AlbumResponseFromJSON,
  AlbumResponseToJSON,
} from "../models/AlbumResponse";
import {
  type AlbumShareLinkBasic,
  AlbumShareLinkBasicFromJSON,
  AlbumShareLinkBasicToJSON,
} from "../models/AlbumShareLinkBasic";
import {
  type AlbumShareLinkInsert,
  AlbumShareLinkInsertFromJSON,
  AlbumShareLinkInsertToJSON,
} from "../models/AlbumShareLinkInsert";
import {
  type AlbumUpdateData,
  AlbumUpdateDataFromJSON,
  AlbumUpdateDataToJSON,
} from "../models/AlbumUpdateData";
import {
  type LoginResponse,
  LoginResponseFromJSON,
  LoginResponseToJSON,
} from "../models/LoginResponse";
import {
  type MediaDescription,
  MediaDescriptionFromJSON,
  MediaDescriptionToJSON,
} from "../models/MediaDescription";
import {
  type MediaResponse,
  MediaResponseFromJSON,
  MediaResponseToJSON,
} from "../models/MediaResponse";
import {
  type ServerConfigResponse,
  ServerConfigResponseFromJSON,
  ServerConfigResponseToJSON,
} from "../models/ServerConfigResponse";
import {
  type SharedAlbumLinkResponse,
  SharedAlbumLinkResponseFromJSON,
  SharedAlbumLinkResponseToJSON,
} from "../models/SharedAlbumLinkResponse";
import {
  type SystemInfoPublic,
  SystemInfoPublicFromJSON,
  SystemInfoPublicToJSON,
} from "../models/SystemInfoPublic";
import {
  type UserInsert,
  UserInsertFromJSON,
  UserInsertToJSON,
} from "../models/UserInsert";
import {
  type UserLogin,
  UserLoginFromJSON,
  UserLoginToJSON,
} from "../models/UserLogin";

export interface RoutesAlbumAddMediaRequest {
  albumAddMedia: Array<AlbumAddMedia>;
}

export interface RoutesCreateAlbumRequest {
  albumInsertData: AlbumInsertData;
}

export interface RoutesCreateAlbumShareLinkRequest {
  albumUuid: string;
  albumShareLinkInsert: AlbumShareLinkInsert;
}

export interface RoutesCreateUserRequest {
  userInsert: UserInsert;
}

export interface RoutesDeleteAlbumRequest {
  albumUuid: string;
}

export interface RoutesDeleteAlbumShareLinkRequest {
  albumShareLinkUuid: string;
}

export interface RoutesGetAlbumShareLinkRequest {
  albumShareLinkUuid: string;
}

export interface RoutesGetAlbumShareLinksRequest {
  albumUuid: string;
}

export interface RoutesGetAlbumStructureRequest {
  albumUuid: string;
}

export interface RoutesGetMediaByUuidRequest {
  mediaUuid: string;
}

export interface RoutesLoginRequest {
  userLogin: UserLogin;
}

export interface RoutesMediaDeleteDescriptionRequest {
  mediaUuid: string;
}

export interface RoutesMediaLikeRequest {
  mediaUuid: string;
}

export interface RoutesMediaUnlikeRequest {
  mediaUuid: string;
}

export interface RoutesMediaUpdateDescriptionRequest {
  mediaUuid: string;
  mediaDescription: MediaDescription;
}

export interface RoutesOidcCallbackRequest {
  provider: string;
  code: string;
  state: string;
}

export interface RoutesOidcLoginRequest {
  provider: string;
}

export interface RoutesUpdateAlbumRequest {
  albumUuid: string;
  albumUpdateData: AlbumUpdateData;
}

export interface RoutesUpdateAlbumShareLinkRequest {
  albumShareLinkUuid: string;
  albumShareLinkInsert: AlbumShareLinkInsert;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Creates request options for routesAlbumAddMedia without sending the request
   */
  async routesAlbumAddMediaRequestOpts(
    requestParameters: RoutesAlbumAddMediaRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumAddMedia"] == null) {
      throw new runtime.RequiredError(
        "albumAddMedia",
        'Required parameter "albumAddMedia" was null or undefined when calling routesAlbumAddMedia().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/media`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: requestParameters["albumAddMedia"]!.map(AlbumAddMediaToJSON),
    };
  }

  /**
   * Adds media to an album
   */
  async routesAlbumAddMediaRaw(
    requestParameters: RoutesAlbumAddMediaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesAlbumAddMediaRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Adds media to an album
   */
  async routesAlbumAddMedia(
    requestParameters: RoutesAlbumAddMediaRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesAlbumAddMediaRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesCreateAlbum without sending the request
   */
  async routesCreateAlbumRequestOpts(
    requestParameters: RoutesCreateAlbumRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumInsertData"] == null) {
      throw new runtime.RequiredError(
        "albumInsertData",
        'Required parameter "albumInsertData" was null or undefined when calling routesCreateAlbum().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: AlbumInsertDataToJSON(requestParameters["albumInsertData"]),
    };
  }

  /**
   * Creates a new album
   */
  async routesCreateAlbumRaw(
    requestParameters: RoutesCreateAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AlbumResponse>> {
    const requestOptions =
      await this.routesCreateAlbumRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AlbumResponseFromJSON(jsonValue)
    );
  }

  /**
   * Creates a new album
   */
  async routesCreateAlbum(
    requestParameters: RoutesCreateAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AlbumResponse> {
    const response = await this.routesCreateAlbumRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesCreateAlbumShareLink without sending the request
   */
  async routesCreateAlbumShareLinkRequestOpts(
    requestParameters: RoutesCreateAlbumShareLinkRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumUuid"] == null) {
      throw new runtime.RequiredError(
        "albumUuid",
        'Required parameter "albumUuid" was null or undefined when calling routesCreateAlbumShareLink().'
      );
    }

    if (requestParameters["albumShareLinkInsert"] == null) {
      throw new runtime.RequiredError(
        "albumShareLinkInsert",
        'Required parameter "albumShareLinkInsert" was null or undefined when calling routesCreateAlbumShareLink().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/{album_uuid}/share/link`;
    urlPath = urlPath.replace(
      "{album_uuid}",
      encodeURIComponent(String(requestParameters["albumUuid"]))
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: AlbumShareLinkInsertToJSON(
        requestParameters["albumShareLinkInsert"]
      ),
    };
  }

  /**
   * Creates a new album share link.
   */
  async routesCreateAlbumShareLinkRaw(
    requestParameters: RoutesCreateAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<SharedAlbumLinkResponse>> {
    const requestOptions =
      await this.routesCreateAlbumShareLinkRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SharedAlbumLinkResponseFromJSON(jsonValue)
    );
  }

  /**
   * Creates a new album share link.
   */
  async routesCreateAlbumShareLink(
    requestParameters: RoutesCreateAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<SharedAlbumLinkResponse> {
    const response = await this.routesCreateAlbumShareLinkRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesCreateUser without sending the request
   */
  async routesCreateUserRequestOpts(
    requestParameters: RoutesCreateUserRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["userInsert"] == null) {
      throw new runtime.RequiredError(
        "userInsert",
        'Required parameter "userInsert" was null or undefined when calling routesCreateUser().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/user`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: UserInsertToJSON(requestParameters["userInsert"]),
    };
  }

  /**
   * Creates a new user
   */
  async routesCreateUserRaw(
    requestParameters: RoutesCreateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesCreateUserRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Creates a new user
   */
  async routesCreateUser(
    requestParameters: RoutesCreateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesCreateUserRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesDeleteAlbum without sending the request
   */
  async routesDeleteAlbumRequestOpts(
    requestParameters: RoutesDeleteAlbumRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumUuid"] == null) {
      throw new runtime.RequiredError(
        "albumUuid",
        'Required parameter "albumUuid" was null or undefined when calling routesDeleteAlbum().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/{album_uuid}`;
    urlPath = urlPath.replace(
      "{album_uuid}",
      encodeURIComponent(String(requestParameters["albumUuid"]))
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Deletes an album
   */
  async routesDeleteAlbumRaw(
    requestParameters: RoutesDeleteAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesDeleteAlbumRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Deletes an album
   */
  async routesDeleteAlbum(
    requestParameters: RoutesDeleteAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesDeleteAlbumRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesDeleteAlbumShareLink without sending the request
   */
  async routesDeleteAlbumShareLinkRequestOpts(
    requestParameters: RoutesDeleteAlbumShareLinkRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumShareLinkUuid"] == null) {
      throw new runtime.RequiredError(
        "albumShareLinkUuid",
        'Required parameter "albumShareLinkUuid" was null or undefined when calling routesDeleteAlbumShareLink().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/share/link/{album_share_link_uuid}`;
    urlPath = urlPath.replace(
      "{album_share_link_uuid}",
      encodeURIComponent(String(requestParameters["albumShareLinkUuid"]))
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Deletes an album share link.
   */
  async routesDeleteAlbumShareLinkRaw(
    requestParameters: RoutesDeleteAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesDeleteAlbumShareLinkRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Deletes an album share link.
   */
  async routesDeleteAlbumShareLink(
    requestParameters: RoutesDeleteAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesDeleteAlbumShareLinkRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesGetAlbumList without sending the request
   */
  async routesGetAlbumListRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Retrieves a list of albums of an authenticated user
   */
  async routesGetAlbumListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<AlbumResponse>>> {
    const requestOptions = await this.routesGetAlbumListRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(AlbumResponseFromJSON)
    );
  }

  /**
   * Retrieves a list of albums of an authenticated user
   */
  async routesGetAlbumList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<AlbumResponse>> {
    const response = await this.routesGetAlbumListRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for routesGetAlbumShareLink without sending the request
   */
  async routesGetAlbumShareLinkRequestOpts(
    requestParameters: RoutesGetAlbumShareLinkRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumShareLinkUuid"] == null) {
      throw new runtime.RequiredError(
        "albumShareLinkUuid",
        'Required parameter "albumShareLinkUuid" was null or undefined when calling routesGetAlbumShareLink().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/share/link/{album_share_link_uuid}`;
    urlPath = urlPath.replace(
      "{album_share_link_uuid}",
      encodeURIComponent(String(requestParameters["albumShareLinkUuid"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Gets basic information about album share link.
   */
  async routesGetAlbumShareLinkRaw(
    requestParameters: RoutesGetAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AlbumShareLinkBasic>> {
    const requestOptions =
      await this.routesGetAlbumShareLinkRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AlbumShareLinkBasicFromJSON(jsonValue)
    );
  }

  /**
   * Gets basic information about album share link.
   */
  async routesGetAlbumShareLink(
    requestParameters: RoutesGetAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AlbumShareLinkBasic> {
    const response = await this.routesGetAlbumShareLinkRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesGetAlbumShareLinks without sending the request
   */
  async routesGetAlbumShareLinksRequestOpts(
    requestParameters: RoutesGetAlbumShareLinksRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumUuid"] == null) {
      throw new runtime.RequiredError(
        "albumUuid",
        'Required parameter "albumUuid" was null or undefined when calling routesGetAlbumShareLinks().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/{album_uuid}/share/link`;
    urlPath = urlPath.replace(
      "{album_uuid}",
      encodeURIComponent(String(requestParameters["albumUuid"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Gets a list of album share links.
   */
  async routesGetAlbumShareLinksRaw(
    requestParameters: RoutesGetAlbumShareLinksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<SharedAlbumLinkResponse>>> {
    const requestOptions =
      await this.routesGetAlbumShareLinksRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(SharedAlbumLinkResponseFromJSON)
    );
  }

  /**
   * Gets a list of album share links.
   */
  async routesGetAlbumShareLinks(
    requestParameters: RoutesGetAlbumShareLinksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<SharedAlbumLinkResponse>> {
    const response = await this.routesGetAlbumShareLinksRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesGetAlbumStructure without sending the request
   */
  async routesGetAlbumStructureRequestOpts(
    requestParameters: RoutesGetAlbumStructureRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumUuid"] == null) {
      throw new runtime.RequiredError(
        "albumUuid",
        'Required parameter "albumUuid" was null or undefined when calling routesGetAlbumStructure().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/{album_uuid}/media`;
    urlPath = urlPath.replace(
      "{album_uuid}",
      encodeURIComponent(String(requestParameters["albumUuid"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Gets a list of media in an album
   */
  async routesGetAlbumStructureRaw(
    requestParameters: RoutesGetAlbumStructureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<MediaResponse>>> {
    const requestOptions =
      await this.routesGetAlbumStructureRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MediaResponseFromJSON)
    );
  }

  /**
   * Gets a list of media in an album
   */
  async routesGetAlbumStructure(
    requestParameters: RoutesGetAlbumStructureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<MediaResponse>> {
    const response = await this.routesGetAlbumStructureRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesGetMediaByUuid without sending the request
   */
  async routesGetMediaByUuidRequestOpts(
    requestParameters: RoutesGetMediaByUuidRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["mediaUuid"] == null) {
      throw new runtime.RequiredError(
        "mediaUuid",
        'Required parameter "mediaUuid" was null or undefined when calling routesGetMediaByUuid().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media/{media_uuid}`;
    urlPath = urlPath.replace(
      "{media_uuid}",
      encodeURIComponent(String(requestParameters["mediaUuid"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a media
   */
  async routesGetMediaByUuidRaw(
    requestParameters: RoutesGetMediaByUuidRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Blob>> {
    const requestOptions =
      await this.routesGetMediaByUuidRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.BlobApiResponse(response);
  }

  /**
   * Returns a media
   */
  async routesGetMediaByUuid(
    requestParameters: RoutesGetMediaByUuidRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Blob> {
    const response = await this.routesGetMediaByUuidRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesGetMediaLikedList without sending the request
   */
  async routesGetMediaLikedListRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media/liked`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a list of liked media.
   */
  async routesGetMediaLikedListRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<MediaResponse>>> {
    const requestOptions = await this.routesGetMediaLikedListRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MediaResponseFromJSON)
    );
  }

  /**
   * Returns a list of liked media.
   */
  async routesGetMediaLikedList(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<MediaResponse>> {
    const response = await this.routesGetMediaLikedListRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for routesGetServerConfig without sending the request
   */
  async routesGetServerConfigRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/public/config`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns server configuration
   */
  async routesGetServerConfigRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ServerConfigResponse>> {
    const requestOptions = await this.routesGetServerConfigRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ServerConfigResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns server configuration
   */
  async routesGetServerConfig(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ServerConfigResponse> {
    const response = await this.routesGetServerConfigRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for routesHealth without sending the request
   */
  async routesHealthRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/health`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async routesHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.routesHealthRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async routesHealth(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesHealthRaw(initOverrides);
  }

  /**
   * Creates request options for routesLogin without sending the request
   */
  async routesLoginRequestOpts(
    requestParameters: RoutesLoginRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["userLogin"] == null) {
      throw new runtime.RequiredError(
        "userLogin",
        'Required parameter "userLogin" was null or undefined when calling routesLogin().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    let urlPath = `/auth/login`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
      body: UserLoginToJSON(requestParameters["userLogin"]),
    };
  }

  /**
   * You must provide either a username or an email together with a password.
   */
  async routesLoginRaw(
    requestParameters: RoutesLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const requestOptions = await this.routesLoginRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LoginResponseFromJSON(jsonValue)
    );
  }

  /**
   * You must provide either a username or an email together with a password.
   */
  async routesLogin(
    requestParameters: RoutesLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.routesLoginRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesLogout without sending the request
   */
  async routesLogoutRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/logout`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Invalidates the session.
   */
  async routesLogoutRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.routesLogoutRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Invalidates the session.
   */
  async routesLogout(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesLogoutRaw(initOverrides);
  }

  /**
   * Creates request options for routesMediaDeleteDescription without sending the request
   */
  async routesMediaDeleteDescriptionRequestOpts(
    requestParameters: RoutesMediaDeleteDescriptionRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["mediaUuid"] == null) {
      throw new runtime.RequiredError(
        "mediaUuid",
        'Required parameter "mediaUuid" was null or undefined when calling routesMediaDeleteDescription().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media/{media_uuid}/description`;
    urlPath = urlPath.replace(
      "{media_uuid}",
      encodeURIComponent(String(requestParameters["mediaUuid"]))
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Deletes description of a media
   */
  async routesMediaDeleteDescriptionRaw(
    requestParameters: RoutesMediaDeleteDescriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesMediaDeleteDescriptionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Deletes description of a media
   */
  async routesMediaDeleteDescription(
    requestParameters: RoutesMediaDeleteDescriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesMediaDeleteDescriptionRaw(
      requestParameters,
      initOverrides
    );
  }

  /**
   * Creates request options for routesMediaLike without sending the request
   */
  async routesMediaLikeRequestOpts(
    requestParameters: RoutesMediaLikeRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["mediaUuid"] == null) {
      throw new runtime.RequiredError(
        "mediaUuid",
        'Required parameter "mediaUuid" was null or undefined when calling routesMediaLike().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media/{media_uuid}/like`;
    urlPath = urlPath.replace(
      "{media_uuid}",
      encodeURIComponent(String(requestParameters["mediaUuid"]))
    );

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Likes the media.
   */
  async routesMediaLikeRaw(
    requestParameters: RoutesMediaLikeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesMediaLikeRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Likes the media.
   */
  async routesMediaLike(
    requestParameters: RoutesMediaLikeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesMediaLikeRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesMediaStructure without sending the request
   */
  async routesMediaStructureRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Gets a list of all media
   */
  async routesMediaStructureRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<MediaResponse>>> {
    const requestOptions = await this.routesMediaStructureRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(MediaResponseFromJSON)
    );
  }

  /**
   * Gets a list of all media
   */
  async routesMediaStructure(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<MediaResponse>> {
    const response = await this.routesMediaStructureRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for routesMediaUnlike without sending the request
   */
  async routesMediaUnlikeRequestOpts(
    requestParameters: RoutesMediaUnlikeRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["mediaUuid"] == null) {
      throw new runtime.RequiredError(
        "mediaUuid",
        'Required parameter "mediaUuid" was null or undefined when calling routesMediaUnlike().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media/{media_uuid}/like`;
    urlPath = urlPath.replace(
      "{media_uuid}",
      encodeURIComponent(String(requestParameters["mediaUuid"]))
    );

    return {
      path: urlPath,
      method: "DELETE",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Unlikes the media.
   */
  async routesMediaUnlikeRaw(
    requestParameters: RoutesMediaUnlikeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesMediaUnlikeRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Unlikes the media.
   */
  async routesMediaUnlike(
    requestParameters: RoutesMediaUnlikeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesMediaUnlikeRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesMediaUpdateDescription without sending the request
   */
  async routesMediaUpdateDescriptionRequestOpts(
    requestParameters: RoutesMediaUpdateDescriptionRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["mediaUuid"] == null) {
      throw new runtime.RequiredError(
        "mediaUuid",
        'Required parameter "mediaUuid" was null or undefined when calling routesMediaUpdateDescription().'
      );
    }

    if (requestParameters["mediaDescription"] == null) {
      throw new runtime.RequiredError(
        "mediaDescription",
        'Required parameter "mediaDescription" was null or undefined when calling routesMediaUpdateDescription().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/media/{media_uuid}/description`;
    urlPath = urlPath.replace(
      "{media_uuid}",
      encodeURIComponent(String(requestParameters["mediaUuid"]))
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: MediaDescriptionToJSON(requestParameters["mediaDescription"]),
    };
  }

  /**
   * Updates description of a media
   */
  async routesMediaUpdateDescriptionRaw(
    requestParameters: RoutesMediaUpdateDescriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesMediaUpdateDescriptionRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Updates description of a media
   */
  async routesMediaUpdateDescription(
    requestParameters: RoutesMediaUpdateDescriptionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesMediaUpdateDescriptionRaw(
      requestParameters,
      initOverrides
    );
  }

  /**
   * Creates request options for routesOidcCallback without sending the request
   */
  async routesOidcCallbackRequestOpts(
    requestParameters: RoutesOidcCallbackRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["provider"] == null) {
      throw new runtime.RequiredError(
        "provider",
        'Required parameter "provider" was null or undefined when calling routesOidcCallback().'
      );
    }

    if (requestParameters["code"] == null) {
      throw new runtime.RequiredError(
        "code",
        'Required parameter "code" was null or undefined when calling routesOidcCallback().'
      );
    }

    if (requestParameters["state"] == null) {
      throw new runtime.RequiredError(
        "state",
        'Required parameter "state" was null or undefined when calling routesOidcCallback().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters["code"] != null) {
      queryParameters["code"] = requestParameters["code"];
    }

    if (requestParameters["state"] != null) {
      queryParameters["state"] = requestParameters["state"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/oidc/{provider}/callback`;
    urlPath = urlPath.replace(
      "{provider}",
      encodeURIComponent(String(requestParameters["provider"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async routesOidcCallbackRaw(
    requestParameters: RoutesOidcCallbackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const requestOptions =
      await this.routesOidcCallbackRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LoginResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async routesOidcCallback(
    requestParameters: RoutesOidcCallbackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.routesOidcCallbackRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for routesOidcLogin without sending the request
   */
  async routesOidcLoginRequestOpts(
    requestParameters: RoutesOidcLoginRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["provider"] == null) {
      throw new runtime.RequiredError(
        "provider",
        'Required parameter "provider" was null or undefined when calling routesOidcLogin().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/oidc/{provider}/login`;
    urlPath = urlPath.replace(
      "{provider}",
      encodeURIComponent(String(requestParameters["provider"]))
    );

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   */
  async routesOidcLoginRaw(
    requestParameters: RoutesOidcLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesOidcLoginRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async routesOidcLogin(
    requestParameters: RoutesOidcLoginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesOidcLoginRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesRefreshToken without sending the request
   */
  async routesRefreshTokenRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/auth/refresh`;

    return {
      path: urlPath,
      method: "POST",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Issues a new access token when a valid refresh token is attached
   */
  async routesRefreshTokenRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const requestOptions = await this.routesRefreshTokenRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      LoginResponseFromJSON(jsonValue)
    );
  }

  /**
   * Issues a new access token when a valid refresh token is attached
   */
  async routesRefreshToken(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.routesRefreshTokenRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for routesScanMedia without sending the request
   */
  async routesScanMediaRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/scan_media`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Searches for new media
   */
  async routesScanMediaRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.routesScanMediaRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Searches for new media
   */
  async routesScanMedia(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesScanMediaRaw(initOverrides);
  }

  /**
   * Creates request options for routesSystemInfoPublic without sending the request
   */
  async routesSystemInfoPublicRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/system/info/public`;

    return {
      path: urlPath,
      method: "GET",
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns the public system information.
   */
  async routesSystemInfoPublicRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<SystemInfoPublic>> {
    const requestOptions = await this.routesSystemInfoPublicRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SystemInfoPublicFromJSON(jsonValue)
    );
  }

  /**
   * Returns the public system information.
   */
  async routesSystemInfoPublic(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<SystemInfoPublic> {
    const response = await this.routesSystemInfoPublicRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for routesUpdateAlbum without sending the request
   */
  async routesUpdateAlbumRequestOpts(
    requestParameters: RoutesUpdateAlbumRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumUuid"] == null) {
      throw new runtime.RequiredError(
        "albumUuid",
        'Required parameter "albumUuid" was null or undefined when calling routesUpdateAlbum().'
      );
    }

    if (requestParameters["albumUpdateData"] == null) {
      throw new runtime.RequiredError(
        "albumUpdateData",
        'Required parameter "albumUpdateData" was null or undefined when calling routesUpdateAlbum().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/{album_uuid}`;
    urlPath = urlPath.replace(
      "{album_uuid}",
      encodeURIComponent(String(requestParameters["albumUuid"]))
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: AlbumUpdateDataToJSON(requestParameters["albumUpdateData"]),
    };
  }

  /**
   * Updates already existing album
   */
  async routesUpdateAlbumRaw(
    requestParameters: RoutesUpdateAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesUpdateAlbumRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Updates already existing album
   */
  async routesUpdateAlbum(
    requestParameters: RoutesUpdateAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesUpdateAlbumRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for routesUpdateAlbumShareLink without sending the request
   */
  async routesUpdateAlbumShareLinkRequestOpts(
    requestParameters: RoutesUpdateAlbumShareLinkRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters["albumShareLinkUuid"] == null) {
      throw new runtime.RequiredError(
        "albumShareLinkUuid",
        'Required parameter "albumShareLinkUuid" was null or undefined when calling routesUpdateAlbumShareLink().'
      );
    }

    if (requestParameters["albumShareLinkInsert"] == null) {
      throw new runtime.RequiredError(
        "albumShareLinkInsert",
        'Required parameter "albumShareLinkInsert" was null or undefined when calling routesUpdateAlbumShareLink().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("BearerAuth", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/album/share/link/{album_share_link_uuid}`;
    urlPath = urlPath.replace(
      "{album_share_link_uuid}",
      encodeURIComponent(String(requestParameters["albumShareLinkUuid"]))
    );

    return {
      path: urlPath,
      method: "PUT",
      headers: headerParameters,
      query: queryParameters,
      body: AlbumShareLinkInsertToJSON(
        requestParameters["albumShareLinkInsert"]
      ),
    };
  }

  /**
   * Updates already existing album share link.
   */
  async routesUpdateAlbumShareLinkRaw(
    requestParameters: RoutesUpdateAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.routesUpdateAlbumShareLinkRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Updates already existing album share link.
   */
  async routesUpdateAlbumShareLink(
    requestParameters: RoutesUpdateAlbumShareLinkRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.routesUpdateAlbumShareLinkRaw(requestParameters, initOverrides);
  }
}
