/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AlbumResponse
 */
export interface AlbumResponse {
  /**
   *
   * @type {Date}
   * @memberof AlbumResponse
   */
  created_at: Date;
  /**
   *
   * @type {string}
   * @memberof AlbumResponse
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof AlbumResponse
   */
  link: string;
  /**
   *
   * @type {string}
   * @memberof AlbumResponse
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof AlbumResponse
   */
  owner_id: number;
  /**
   *
   * @type {string}
   * @memberof AlbumResponse
   */
  thumbnail_link?: string | null;
}

/**
 * Check if a given object implements the AlbumResponse interface.
 */
export function instanceOfAlbumResponse(value: object): value is AlbumResponse {
  if (!("created_at" in value) || value["created_at"] === undefined)
    return false;
  if (!("link" in value) || value["link"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("owner_id" in value) || value["owner_id"] === undefined) return false;
  return true;
}

export function AlbumResponseFromJSON(json: any): AlbumResponse {
  return AlbumResponseFromJSONTyped(json, false);
}

export function AlbumResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AlbumResponse {
  if (json == null) {
    return json;
  }
  return {
    created_at: new Date(json["created_at"]),
    description: json["description"] == null ? undefined : json["description"],
    link: json["link"],
    name: json["name"],
    owner_id: json["owner_id"],
    thumbnail_link:
      json["thumbnail_link"] == null ? undefined : json["thumbnail_link"],
  };
}

export function AlbumResponseToJSON(json: any): AlbumResponse {
  return AlbumResponseToJSONTyped(json, false);
}

export function AlbumResponseToJSONTyped(
  value?: AlbumResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value["created_at"].toISOString(),
    description: value["description"],
    link: value["link"],
    name: value["name"],
    owner_id: value["owner_id"],
    thumbnail_link: value["thumbnail_link"],
  };
}
