/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AlbumInsertData
 */
export interface AlbumInsertData {
  /**
   *
   * @type {string}
   * @memberof AlbumInsertData
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof AlbumInsertData
   */
  name: string;
}

/**
 * Check if a given object implements the AlbumInsertData interface.
 */
export function instanceOfAlbumInsertData(
  value: object
): value is AlbumInsertData {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function AlbumInsertDataFromJSON(json: any): AlbumInsertData {
  return AlbumInsertDataFromJSONTyped(json, false);
}

export function AlbumInsertDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AlbumInsertData {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"] == null ? undefined : json["description"],
    name: json["name"],
  };
}

export function AlbumInsertDataToJSON(json: any): AlbumInsertData {
  return AlbumInsertDataToJSONTyped(json, false);
}

export function AlbumInsertDataToJSONTyped(
  value?: AlbumInsertData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    description: value["description"],
    name: value["name"],
  };
}
