/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AlbumAddMedia
 */
export interface AlbumAddMedia {
  /**
   *
   * @type {string}
   * @memberof AlbumAddMedia
   */
  album_uuid: string;
  /**
   *
   * @type {string}
   * @memberof AlbumAddMedia
   */
  media_uuid: string;
}

/**
 * Check if a given object implements the AlbumAddMedia interface.
 */
export function instanceOfAlbumAddMedia(value: object): value is AlbumAddMedia {
  if (!("album_uuid" in value) || value["album_uuid"] === undefined)
    return false;
  if (!("media_uuid" in value) || value["media_uuid"] === undefined)
    return false;
  return true;
}

export function AlbumAddMediaFromJSON(json: any): AlbumAddMedia {
  return AlbumAddMediaFromJSONTyped(json, false);
}

export function AlbumAddMediaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AlbumAddMedia {
  if (json == null) {
    return json;
  }
  return {
    album_uuid: json["album_uuid"],
    media_uuid: json["media_uuid"],
  };
}

export function AlbumAddMediaToJSON(json: any): AlbumAddMedia {
  return AlbumAddMediaToJSONTyped(json, false);
}

export function AlbumAddMediaToJSONTyped(
  value?: AlbumAddMedia | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    album_uuid: value["album_uuid"],
    media_uuid: value["media_uuid"],
  };
}
