/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AlbumShareLinkBasic
 */
export interface AlbumShareLinkBasic {
  /**
   *
   * @type {string}
   * @memberof AlbumShareLinkBasic
   */
  album_uuid: string;
  /**
   *
   * @type {boolean}
   * @memberof AlbumShareLinkBasic
   */
  is_expired: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AlbumShareLinkBasic
   */
  is_password_protected: boolean;
}

/**
 * Check if a given object implements the AlbumShareLinkBasic interface.
 */
export function instanceOfAlbumShareLinkBasic(
  value: object
): value is AlbumShareLinkBasic {
  if (!("album_uuid" in value) || value["album_uuid"] === undefined)
    return false;
  if (!("is_expired" in value) || value["is_expired"] === undefined)
    return false;
  if (
    !("is_password_protected" in value) ||
    value["is_password_protected"] === undefined
  )
    return false;
  return true;
}

export function AlbumShareLinkBasicFromJSON(json: any): AlbumShareLinkBasic {
  return AlbumShareLinkBasicFromJSONTyped(json, false);
}

export function AlbumShareLinkBasicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AlbumShareLinkBasic {
  if (json == null) {
    return json;
  }
  return {
    album_uuid: json["album_uuid"],
    is_expired: json["is_expired"],
    is_password_protected: json["is_password_protected"],
  };
}

export function AlbumShareLinkBasicToJSON(json: any): AlbumShareLinkBasic {
  return AlbumShareLinkBasicToJSONTyped(json, false);
}

export function AlbumShareLinkBasicToJSONTyped(
  value?: AlbumShareLinkBasic | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    album_uuid: value["album_uuid"],
    is_expired: value["is_expired"],
    is_password_protected: value["is_password_protected"],
  };
}
