/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AlbumUpdateData
 */
export interface AlbumUpdateData {
  /**
   *
   * @type {string}
   * @memberof AlbumUpdateData
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof AlbumUpdateData
   */
  name?: string | null;
}

/**
 * Check if a given object implements the AlbumUpdateData interface.
 */
export function instanceOfAlbumUpdateData(
  value: object
): value is AlbumUpdateData {
  return true;
}

export function AlbumUpdateDataFromJSON(json: any): AlbumUpdateData {
  return AlbumUpdateDataFromJSONTyped(json, false);
}

export function AlbumUpdateDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AlbumUpdateData {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"] == null ? undefined : json["description"],
    name: json["name"] == null ? undefined : json["name"],
  };
}

export function AlbumUpdateDataToJSON(json: any): AlbumUpdateData {
  return AlbumUpdateDataToJSONTyped(json, false);
}

export function AlbumUpdateDataToJSONTyped(
  value?: AlbumUpdateData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    description: value["description"],
    name: value["name"],
  };
}
