/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AlbumShareLinkInsert
 */
export interface AlbumShareLinkInsert {
  /**
   *
   * @type {Date}
   * @memberof AlbumShareLinkInsert
   */
  expiration?: Date | null;
  /**
   *
   * @type {string}
   * @memberof AlbumShareLinkInsert
   */
  password?: string | null;
}

/**
 * Check if a given object implements the AlbumShareLinkInsert interface.
 */
export function instanceOfAlbumShareLinkInsert(
  value: object
): value is AlbumShareLinkInsert {
  return true;
}

export function AlbumShareLinkInsertFromJSON(json: any): AlbumShareLinkInsert {
  return AlbumShareLinkInsertFromJSONTyped(json, false);
}

export function AlbumShareLinkInsertFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AlbumShareLinkInsert {
  if (json == null) {
    return json;
  }
  return {
    expiration:
      json["expiration"] == null ? undefined : new Date(json["expiration"]),
    password: json["password"] == null ? undefined : json["password"],
  };
}

export function AlbumShareLinkInsertToJSON(json: any): AlbumShareLinkInsert {
  return AlbumShareLinkInsertToJSONTyped(json, false);
}

export function AlbumShareLinkInsertToJSONTyped(
  value?: AlbumShareLinkInsert | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    expiration:
      value["expiration"] == null
        ? value["expiration"]
        : value["expiration"].toISOString(),
    password: value["password"],
  };
}
