/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AuthPolicyPublic
 */
export interface AuthPolicyPublic {
  /**
   *
   * @type {boolean}
   * @memberof AuthPolicyPublic
   */
  disable_local_auth: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AuthPolicyPublic
   */
  disable_local_signups: boolean;
}

/**
 * Check if a given object implements the AuthPolicyPublic interface.
 */
export function instanceOfAuthPolicyPublic(
  value: object
): value is AuthPolicyPublic {
  if (
    !("disable_local_auth" in value) ||
    value["disable_local_auth"] === undefined
  )
    return false;
  if (
    !("disable_local_signups" in value) ||
    value["disable_local_signups"] === undefined
  )
    return false;
  return true;
}

export function AuthPolicyPublicFromJSON(json: any): AuthPolicyPublic {
  return AuthPolicyPublicFromJSONTyped(json, false);
}

export function AuthPolicyPublicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthPolicyPublic {
  if (json == null) {
    return json;
  }
  return {
    disable_local_auth: json["disable_local_auth"],
    disable_local_signups: json["disable_local_signups"],
  };
}

export function AuthPolicyPublicToJSON(json: any): AuthPolicyPublic {
  return AuthPolicyPublicToJSONTyped(json, false);
}

export function AuthPolicyPublicToJSONTyped(
  value?: AuthPolicyPublic | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    disable_local_auth: value["disable_local_auth"],
    disable_local_signups: value["disable_local_signups"],
  };
}
