/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { OidcProviderPublic } from "./OidcProviderPublic";
import {
  OidcProviderPublicFromJSON,
  OidcProviderPublicFromJSONTyped,
  OidcProviderPublicToJSON,
  OidcProviderPublicToJSONTyped,
} from "./OidcProviderPublic";
import type { AuthPolicyPublic } from "./AuthPolicyPublic";
import {
  AuthPolicyPublicFromJSON,
  AuthPolicyPublicFromJSONTyped,
  AuthPolicyPublicToJSON,
  AuthPolicyPublicToJSONTyped,
} from "./AuthPolicyPublic";

/**
 *
 * @export
 * @interface AuthConfig
 */
export interface AuthConfig {
  /**
   *
   * @type {Array<OidcProviderPublic>}
   * @memberof AuthConfig
   */
  oidc: Array<OidcProviderPublic>;
  /**
   *
   * @type {AuthPolicyPublic}
   * @memberof AuthConfig
   */
  policy: AuthPolicyPublic;
}

/**
 * Check if a given object implements the AuthConfig interface.
 */
export function instanceOfAuthConfig(value: object): value is AuthConfig {
  if (!("oidc" in value) || value["oidc"] === undefined) return false;
  if (!("policy" in value) || value["policy"] === undefined) return false;
  return true;
}

export function AuthConfigFromJSON(json: any): AuthConfig {
  return AuthConfigFromJSONTyped(json, false);
}

export function AuthConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthConfig {
  if (json == null) {
    return json;
  }
  return {
    oidc: (json["oidc"] as Array<any>).map(OidcProviderPublicFromJSON),
    policy: AuthPolicyPublicFromJSON(json["policy"]),
  };
}

export function AuthConfigToJSON(json: any): AuthConfig {
  return AuthConfigToJSONTyped(json, false);
}

export function AuthConfigToJSONTyped(
  value?: AuthConfig | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    oidc: (value["oidc"] as Array<any>).map(OidcProviderPublicToJSON),
    policy: AuthPolicyPublicToJSON(value["policy"]),
  };
}
