/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AuthPolicyPublic } from "./auth-policy-public";
// May contain unused imports in some cases
// @ts-ignore
import type { OidcProviderPublic } from "./oidc-provider-public";

export interface AuthConfig {
  oidc: Array<OidcProviderPublic>;
  policy: AuthPolicyPublic;
}
