/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserInfo } from "./UserInfo";
import {
  UserInfoFromJSON,
  UserInfoFromJSONTyped,
  UserInfoToJSON,
  UserInfoToJSONTyped,
} from "./UserInfo";

/**
 * Response when logging in.
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  bearer_token: string;
  /**
   *
   * @type {UserInfo}
   * @memberof LoginResponse
   */
  user_info: UserInfo;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
  if (!("bearer_token" in value) || value["bearer_token"] === undefined)
    return false;
  if (!("user_info" in value) || value["user_info"] === undefined) return false;
  return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
  return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LoginResponse {
  if (json == null) {
    return json;
  }
  return {
    bearer_token: json["bearer_token"],
    user_info: UserInfoFromJSON(json["user_info"]),
  };
}

export function LoginResponseToJSON(json: any): LoginResponse {
  return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(
  value?: LoginResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    bearer_token: value["bearer_token"],
    user_info: UserInfoToJSON(value["user_info"]),
  };
}
