/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MediaResponse
 */
export interface MediaResponse {
  /**
   *
   * @type {Date}
   * @memberof MediaResponse
   */
  date_taken?: Date | null;
  /**
   *
   * @type {string}
   * @memberof MediaResponse
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof MediaResponse
   */
  filename: string;
  /**
   *
   * @type {number}
   * @memberof MediaResponse
   */
  height: number;
  /**
   *
   * @type {number}
   * @memberof MediaResponse
   */
  owner_id: number;
  /**
   *
   * @type {string}
   * @memberof MediaResponse
   */
  uuid: string;
  /**
   *
   * @type {number}
   * @memberof MediaResponse
   */
  width: number;
}

/**
 * Check if a given object implements the MediaResponse interface.
 */
export function instanceOfMediaResponse(value: object): value is MediaResponse {
  if (!("filename" in value) || value["filename"] === undefined) return false;
  if (!("height" in value) || value["height"] === undefined) return false;
  if (!("owner_id" in value) || value["owner_id"] === undefined) return false;
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  if (!("width" in value) || value["width"] === undefined) return false;
  return true;
}

export function MediaResponseFromJSON(json: any): MediaResponse {
  return MediaResponseFromJSONTyped(json, false);
}

export function MediaResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MediaResponse {
  if (json == null) {
    return json;
  }
  return {
    date_taken:
      json["date_taken"] == null ? undefined : new Date(json["date_taken"]),
    description: json["description"] == null ? undefined : json["description"],
    filename: json["filename"],
    height: json["height"],
    owner_id: json["owner_id"],
    uuid: json["uuid"],
    width: json["width"],
  };
}

export function MediaResponseToJSON(json: any): MediaResponse {
  return MediaResponseToJSONTyped(json, false);
}

export function MediaResponseToJSONTyped(
  value?: MediaResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    date_taken:
      value["date_taken"] == null
        ? value["date_taken"]
        : value["date_taken"].toISOString(),
    description: value["description"],
    filename: value["filename"],
    height: value["height"],
    owner_id: value["owner_id"],
    uuid: value["uuid"],
    width: value["width"],
  };
}
