/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface MediaDescription
 */
export interface MediaDescription {
  /**
   *
   * @type {string}
   * @memberof MediaDescription
   */
  description?: string | null;
}

/**
 * Check if a given object implements the MediaDescription interface.
 */
export function instanceOfMediaDescription(
  value: object
): value is MediaDescription {
  return true;
}

export function MediaDescriptionFromJSON(json: any): MediaDescription {
  return MediaDescriptionFromJSONTyped(json, false);
}

export function MediaDescriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MediaDescription {
  if (json == null) {
    return json;
  }
  return {
    description: json["description"] == null ? undefined : json["description"],
  };
}

export function MediaDescriptionToJSON(json: any): MediaDescription {
  return MediaDescriptionToJSONTyped(json, false);
}

export function MediaDescriptionToJSONTyped(
  value?: MediaDescription | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    description: value["description"],
  };
}
