/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface OidcProviderPublic
 */
export interface OidcProviderPublic {
  /**
   *
   * @type {string}
   * @memberof OidcProviderPublic
   */
  display_name: string;
  /**
   *
   * @type {string}
   * @memberof OidcProviderPublic
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof OidcProviderPublic
   */
  login_url: string;
}

/**
 * Check if a given object implements the OidcProviderPublic interface.
 */
export function instanceOfOidcProviderPublic(
  value: object
): value is OidcProviderPublic {
  if (!("display_name" in value) || value["display_name"] === undefined)
    return false;
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("login_url" in value) || value["login_url"] === undefined) return false;
  return true;
}

export function OidcProviderPublicFromJSON(json: any): OidcProviderPublic {
  return OidcProviderPublicFromJSONTyped(json, false);
}

export function OidcProviderPublicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OidcProviderPublic {
  if (json == null) {
    return json;
  }
  return {
    display_name: json["display_name"],
    key: json["key"],
    login_url: json["login_url"],
  };
}

export function OidcProviderPublicToJSON(json: any): OidcProviderPublic {
  return OidcProviderPublicToJSONTyped(json, false);
}

export function OidcProviderPublicToJSONTyped(
  value?: OidcProviderPublic | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    display_name: value["display_name"],
    key: value["key"],
    login_url: value["login_url"],
  };
}
