/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AuthConfig } from "./AuthConfig";
import {
  AuthConfigFromJSON,
  AuthConfigFromJSONTyped,
  AuthConfigToJSON,
  AuthConfigToJSONTyped,
} from "./AuthConfig";

/**
 *
 * @export
 * @interface ServerConfigResponse
 */
export interface ServerConfigResponse {
  /**
   *
   * @type {AuthConfig}
   * @memberof ServerConfigResponse
   */
  auth: AuthConfig;
}

/**
 * Check if a given object implements the ServerConfigResponse interface.
 */
export function instanceOfServerConfigResponse(
  value: object
): value is ServerConfigResponse {
  if (!("auth" in value) || value["auth"] === undefined) return false;
  return true;
}

export function ServerConfigResponseFromJSON(json: any): ServerConfigResponse {
  return ServerConfigResponseFromJSONTyped(json, false);
}

export function ServerConfigResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ServerConfigResponse {
  if (json == null) {
    return json;
  }
  return {
    auth: AuthConfigFromJSON(json["auth"]),
  };
}

export function ServerConfigResponseToJSON(json: any): ServerConfigResponse {
  return ServerConfigResponseToJSONTyped(json, false);
}

export function ServerConfigResponseToJSONTyped(
  value?: ServerConfigResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    auth: AuthConfigToJSON(value["auth"]),
  };
}
