/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SharedAlbumLinkResponse
 */
export interface SharedAlbumLinkResponse {
  /**
   *
   * @type {Date}
   * @memberof SharedAlbumLinkResponse
   */
  expiration?: Date | null;
  /**
   *
   * @type {string}
   * @memberof SharedAlbumLinkResponse
   */
  uuid: string;
}

/**
 * Check if a given object implements the SharedAlbumLinkResponse interface.
 */
export function instanceOfSharedAlbumLinkResponse(
  value: object
): value is SharedAlbumLinkResponse {
  if (!("uuid" in value) || value["uuid"] === undefined) return false;
  return true;
}

export function SharedAlbumLinkResponseFromJSON(
  json: any
): SharedAlbumLinkResponse {
  return SharedAlbumLinkResponseFromJSONTyped(json, false);
}

export function SharedAlbumLinkResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SharedAlbumLinkResponse {
  if (json == null) {
    return json;
  }
  return {
    expiration:
      json["expiration"] == null ? undefined : new Date(json["expiration"]),
    uuid: json["uuid"],
  };
}

export function SharedAlbumLinkResponseToJSON(
  json: any
): SharedAlbumLinkResponse {
  return SharedAlbumLinkResponseToJSONTyped(json, false);
}

export function SharedAlbumLinkResponseToJSONTyped(
  value?: SharedAlbumLinkResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    expiration:
      value["expiration"] == null
        ? value["expiration"]
        : value["expiration"].toISOString(),
    uuid: value["uuid"],
  };
}
