/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SystemInfoPublic
 */
export interface SystemInfoPublic {
  /**
   *
   * @type {string}
   * @memberof SystemInfoPublic
   */
  operatingSystem: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfoPublic
   */
  serverName: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfoPublic
   */
  serverVersion: string;
  /**
   *
   * @type {string}
   * @memberof SystemInfoPublic
   */
  systemArchitecture: string;
}

/**
 * Check if a given object implements the SystemInfoPublic interface.
 */
export function instanceOfSystemInfoPublic(
  value: object
): value is SystemInfoPublic {
  if (!("operatingSystem" in value) || value["operatingSystem"] === undefined)
    return false;
  if (!("serverName" in value) || value["serverName"] === undefined)
    return false;
  if (!("serverVersion" in value) || value["serverVersion"] === undefined)
    return false;
  if (
    !("systemArchitecture" in value) ||
    value["systemArchitecture"] === undefined
  )
    return false;
  return true;
}

export function SystemInfoPublicFromJSON(json: any): SystemInfoPublic {
  return SystemInfoPublicFromJSONTyped(json, false);
}

export function SystemInfoPublicFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SystemInfoPublic {
  if (json == null) {
    return json;
  }
  return {
    operatingSystem: json["operatingSystem"],
    serverName: json["serverName"],
    serverVersion: json["serverVersion"],
    systemArchitecture: json["systemArchitecture"],
  };
}

export function SystemInfoPublicToJSON(json: any): SystemInfoPublic {
  return SystemInfoPublicToJSONTyped(json, false);
}

export function SystemInfoPublicToJSONTyped(
  value?: SystemInfoPublic | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    operatingSystem: value["operatingSystem"],
    serverName: value["serverName"],
    serverVersion: value["serverVersion"],
    systemArchitecture: value["systemArchitecture"],
  };
}
