/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserInsert
 */
export interface UserInsert {
  /**
   *
   * @type {string}
   * @memberof UserInsert
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof UserInsert
   */
  password?: string | null;
  /**
   *
   * @type {string}
   * @memberof UserInsert
   */
  username: string;
}

/**
 * Check if a given object implements the UserInsert interface.
 */
export function instanceOfUserInsert(value: object): value is UserInsert {
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("username" in value) || value["username"] === undefined) return false;
  return true;
}

export function UserInsertFromJSON(json: any): UserInsert {
  return UserInsertFromJSONTyped(json, false);
}

export function UserInsertFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserInsert {
  if (json == null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"] == null ? undefined : json["password"],
    username: json["username"],
  };
}

export function UserInsertToJSON(json: any): UserInsert {
  return UserInsertToJSONTyped(json, false);
}

export function UserInsertToJSONTyped(
  value?: UserInsert | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value["email"],
    password: value["password"],
    username: value["username"],
  };
}
