/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: iTzBoboCz@users.noreply.github.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Used for receiving login data.
 * @export
 * @interface UserLogin
 */
export interface UserLogin {
  /**
   *
   * @type {string}
   * @memberof UserLogin
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof UserLogin
   */
  username_or_email: string;
}

/**
 * Check if a given object implements the UserLogin interface.
 */
export function instanceOfUserLogin(value: object): value is UserLogin {
  if (!("password" in value) || value["password"] === undefined) return false;
  if (
    !("username_or_email" in value) ||
    value["username_or_email"] === undefined
  )
    return false;
  return true;
}

export function UserLoginFromJSON(json: any): UserLogin {
  return UserLoginFromJSONTyped(json, false);
}

export function UserLoginFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserLogin {
  if (json == null) {
    return json;
  }
  return {
    password: json["password"],
    username_or_email: json["username_or_email"],
  };
}

export function UserLoginToJSON(json: any): UserLogin {
  return UserLoginToJSONTyped(json, false);
}

export function UserLoginToJSONTyped(
  value?: UserLogin | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    password: value["password"],
    username_or_email: value["username_or_email"],
  };
}
