/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AlbumShareLinkBasic
 */
export interface AlbumShareLinkBasic {
  /**
   *
   * @type {string}
   * @memberof AlbumShareLinkBasic
   */
  album_uuid: string;
  /**
   *
   * @type {boolean}
   * @memberof AlbumShareLinkBasic
   */
  is_expired: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AlbumShareLinkBasic
   */
  is_password_protected: boolean;
}
