/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Encoded bearer token # Example decode an encoded bearer token ``` let encoded_token = Claims::new(1).encode().unwrap();  let decoded_token = encoded_token.decode(); ```
 * @export
 * @interface ClaimsEncoded
 */
export interface ClaimsEncoded {
  /**
   *
   * @type {string}
   * @memberof ClaimsEncoded
   */
  encoded_claims: string;
}
