/* tslint:disable */
/* eslint-disable */
/**
 * galera
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Struct for signing in.
 * @export
 * @interface UserLogin
 */
export interface UserLogin {
  /**
   *
   * @type {string}
   * @memberof UserLogin
   */
  email?: string | null;
  /**
   *
   * @type {string}
   * @memberof UserLogin
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof UserLogin
   */
  username?: string | null;
}
